sonar.projectKey=orca123456_jmcfi-postflow
sonar.organization=bixby
sonar.projectName=JMCFI PostFlow
sonar.sourceEncoding=UTF-8

sonar.sources=backend/app,backend/routes,backend/config,backend/database,frontend-rn/app,frontend-rn/components,frontend-rn/constants,frontend-rn/services

sonar.exclusions=**/vendor/**,**/node_modules/**,**/storage/**,**/bootstrap/cache/**,**/.expo/**,**/dist/**,**/build/**,**/.env,**/*.sqlite,**/*.log
sonar.coverage.exclusions=**/*
